# Assignment 2
## Name :- Ravi Kumar
## Reg. no.:- 24-27-24
## Programme:- Data Science- Tool and Technique


In [39]:
#Problem 1:

#part a:Create a variable named var1 that stores an array of numbers from 0 to 30.
import numpy as np
var1=np.arange(0,30)
print("Array:\n",var1,'\n','shape:',var1.shape)

#part b:Change var2 to a validly-shaped two-dimensional matrix
var2=var1.reshape([6,5])
print(var2,'\n','shape:',var2.shape)

#part c:Change var2 to a validly-shaped three-dimensional matrix
var3=var1.reshape(2,3,5)
print(var3 ,'\n','Shape:',var3.shape)

#part d:Use two-dimensional array indexing to set the first value in the second row of var2to -1
var2[2,0]=-1
print('New_var2:\n ',var2)
print('New_var1:\n',var1,'\nNew_var3:\n',var3)

#part e:
#(i)Sum var3 over its second dimension
sum1=np.sum(var3,axis=1)
print("(i)Sum var3 over 2nd Dimension:\n",sum1)
#(ii) Sum var3 over its third dimension
sum2=np.sum(var3,axis=2)
print("(ii)Sum var3 over 3nd Dimension:\n",sum2)
#(iii)Sum var3 over both its first and third dimensions
sum3=np.sum(var3,axis=(0,2))
print("Sum var3 over 1st and 3rd Dimension:\n",sum3)

#part f:
#(i)Slice out the second row of var2 
slice1=var2[1,:]
print('(i) Second row of var2:\n',slice1)
#(ii) Slice out the last column of var2 using the -1 notation
slice2=var2[:,-1]
print('(ii)Last column of var2:\n',slice2)
#(iii) Slice out the top right 2 × 2 submatrix of var2
slice3=var2[0:2,3:]
print('(iii)  Top right 2 × 2 submatrix of var2:\n',slice3)



Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 
 shape: (30,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 
 shape: (6, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 
 Shape: (2, 3, 5)
New_var2:
  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
New_var1:
 [ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 
New_var3:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [-1 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(i)Sum var3 over 2nd Dimension:
 [[ 4 18 21 24 27]
 [60 63 66 69 72]]
(ii)Sum var3 over 3nd Dimension:
 [[ 10  35  49]
 [ 85 110 135]]
Sum var3 over 1st and 3rd Dimension:
 [ 95 145 184]
(i) Second row of var2:
 [5 6 7 8 9]
(ii)Last column of var2:
 [ 4  9 14 19 24 2

In [41]:
#Problem 2:

#part a: create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function
array1=np.arange(10)
print(array1)
vector=array1+1
print('vector:',vector)

#part b: create a 10 × 10 matrix A in which Ai j = i + j. 

i=vector
j=vector.reshape(10,1)
matrixA=i+j
print('10 × 10 matrix A :\n',matrixA)

#part c,d:Imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them.


import numpy.random as npr

data = np.exp(npr.randn  (50,5)  )
print ('lognormal matrix:\n',data)
mean1=np.mean(data)
print('mean of lognormal matrix:\n',mean1)
std1=np.std(data)
print('Standard deviation of lognormal matrix:\n',std1)
standardize_data1=(data-mean1)/std1
print('standardize matrix:\n',standardize_data1)
print('mean of standardize matrix:\n',np.mean(standardize_data1))
print('Standard deviation of standardize matrix:\n',np.std(standardize_data1))


#part e:compute the mean and standard deviation of each column.

mean2=np.mean(data,axis=0)
print('mean of column:',mean2,'\nlength of mean:',len(mean2))
std2=np.std(data,axis=0)
print('Standard deviation of column:',std2,'\nlength of mean:',len(std2))

#part f:compute the mean and standard deviation ofthe columns of normalized

normalized=data-mean2
normalized/=std2
print('Normalized Matrix:\n',normalized)
normalized_mean=np.mean(normalized,axis=0)
normalized_std=np.std(normalized,axis=0)
print("mean:\n",normalized_mean)
print('standard deviation:\n',normalized_std)



[0 1 2 3 4 5 6 7 8 9]
vector: [ 1  2  3  4  5  6  7  8  9 10]
10 × 10 matrix A :
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]
lognormal matrix:
 [[0.16857582 2.98116552 1.46872036 0.93189086 0.25205993]
 [0.50493245 0.87404208 0.53175298 0.14535504 0.22373464]
 [0.94163553 7.34067412 1.18208456 5.24478387 0.59865676]
 [0.3743614  3.02713015 0.74673479 0.16870992 4.7916008 ]
 [1.36257839 9.0940336  0.70094299 0.11267548 1.5533816 ]
 [0.30020388 0.13320433 0.5475997  0.12613889 1.06212274]
 [1.25977532 2.28437866 1.11174583 0.37496046 0.41685067]
 [1.36414714 0.69101947 1.31911559 0.5819356  2.30538519]
 [1.26811157 0.78040043 0.79830416 2.46135527 2.49332848]
 [2.14563891 1.02825126 1.26718414 0.60812134 

In [45]:
#Problem 3

#part a:Use your function for N = 12, store it in variable named vander

def vandermonde (N):
    vec = np.arange (N)+1
    vander = vec[:,np.newaxis] ** np.arange(N)
    return vander
vander=vandermonde(12)
print(vander)    

#part b. Create a vector of all ones, of length 12 and call it x

x=np.ones(12,dtype=np.int64)
print(x)

b=np.dot(vander,x)  
print(b)

#part c:solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert V and multiply it by b

invert_V=np.linalg.inv(vander)
estimated_x1=invert_V @ b
print('Estimated x by inverted vander:\n',estimated_x1)
#Comment:some data points are exactly same to original X but there is some difference between estimated x and original x vector.It is not accurate.

#part d:solve the same linear system using solve.

estimated_x2=np.linalg.solve(vander,b)
print('Estimated x by solve function:\n',estimated_x2)

#comment:Here also some points are same to original x and some point throughing some difference between original x and estimated x.but solve funcion giving more accurate than invert method.

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57